import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar';
import Work from '../components/Work';
import Skills from '../components/Skills';
import AboutMe from '../components/AboutMe';
import ContactForm from '../components/ContactForm';
import Image from 'next/image'
import hero from "../public/neil-johnson-hero.jpg";
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faLinkedinIn } from '@fortawesome/free-brands-svg-icons'

const Home: NextPage = () => {
  return (
    <>
      <Navbar />
      <main className='main'>
        <div id="home" className={styles.hero}>
          <Image
            src={hero}
            alt="sunset"
            layout="fill"
            objectFit="cover"
            quality={100}
            priority
          />
          <div className={styles.heroContainer}>
            <div className={styles.heroContent}>
              <h1 className={styles.intro}>Hi. I&apos;m Neil.<br />A Full Stack Engineer.</h1>
              <div>
                <a href="https://www.linkedin.com/in/johnson-neil/" target="_blank" rel="noopener noreferrer">
                  <FontAwesomeIcon className={styles.heroIcon} icon={faLinkedinIn} size="2x" />
                </a>
                <a href="https://github.com/nxjohnson" target="_blank" rel="noopener noreferrer">
                  <FontAwesomeIcon className={styles.heroIcon} icon={faGithub} size="2x" />
                </a>

            </div>
            </div>
          </div>
        </div>
        <div className={styles.sectionContainer}>
          <Work />
          <Skills />
          <AboutMe />
        </div>
        <ContactForm />
      </main>
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
